version: "3.9"
services:
    db:
        image: postgres
        restart: always
        volumes: 
            - ../db:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    pgadmin: 
        image: dpage/pgadmin4
        restart: always 
        ports:
            - "5050:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}" 

