version: "3.9"
services:
    db:
        build:
            context: ../database
            dockerfile: ../docker/Dockerfile.pg 
        container_name: database
        restart: always
        volumes: 
            - ../db:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    
    pgadmin: 
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always 
        depends_on: 
            - db
        ports:
            - "5050:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
     
    redis:
        build:
            context: .
            dockerfile: Dockerfile.redis
        container_name: redis
        restart: always
        volumes:
            - ../redis:/data


    userprofile:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../user-profile
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.userProfile
        container_name: micro_user_prof
        depends_on: 
            - db
            - redis
        restart: always
        environment: 
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_HOST: "db"


