version: "3.9"
services:
    db:
        build:
            context: ../database
            dockerfile: ../docker/Dockerfile.pg 
        container_name: database
        restart: always
        volumes: 
            - ../db:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    
    pgadmin: 
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always 
        depends_on: 
            - db
        ports:
            - "5050:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
     
    redis:
        build:
            context: .
            dockerfile: Dockerfile.redis
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ../redis:/data

    authentication:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../authentication
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.authentication
        container_name: ms_auth
        depends_on: 
            - db
            - redis
        restart: always
        ports:
            - "5000:3000"
        environment: 
            NODE_ENV: "production"
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_HOST: "db" 
            DB_NAME: "auth"
            REDIS_HOST: "redis"    

    userprofile:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../user-profile
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.userProfile
        container_name: ms_user_profile
        depends_on: 
            - db
            - redis
        restart: always
        environment: 
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_NAME: "user_profile"
            DB_HOST: "db"


