version: "3.9"
services:
    db:
        build:
            context: ../database
            dockerfile: ../docker/Dockerfile.pg 
        container_name: database
        restart: always
        volumes: 
            - ../db:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    
    pgadmin: 
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always 
        depends_on: 
            - db
        ports:
            - "5050:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
     
    redis:
        image: redis:latest
        command: redis-server --appendonly yes 
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ../redis/data:/data
