-- Microservices databases

CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON DATABASE auth TO postgres;

CREATE DATABASE user_profile;
GRANT ALL PRIVILEGES ON DATABASE user_profile TO postgres;

CREATE DATABASE questions;
GRANT ALL PRIVILEGES ON DATABASE questions TO postgres;

CREATE DATABASE keywords;
GRANT ALL PRIVILEGES ON DATABASE keywords TO postgres;

CREATE DATABASE answers;
GRANT ALL PRIVILEGES ON DATABASE answers TO postgres;

-- SOA database

CREATE DATABASE soa;
GRANT ALL PRIVILEGES ON DATABASE soa TO postgres;

