CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON DATABASE auth TO postgres;

CREATE DATABASE user_profile;
GRANT ALL PRIVILEGES ON DATABASE user_profile TO postgres;

CREATE DATABASE questions;
GRANT ALL PRIVILEGES ON DATABASE questions TO postgres;
