version: "3.9"
services:
    authentication:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../microservices/authentication
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.authentication
        container_name: ms_auth
        depends_on: 
            - db
            - redis
        restart: always
        ports:
            - "5000:3000"
        environment: 
            NODE_ENV: "production"
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_HOST: "db" 
            DB_NAME: "auth"
            REDIS_HOST: "redis"  
    
    userprofile:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../microservices/user-profile
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.userProfile
        container_name: ms_user_profile
        depends_on: 
            - db
            - redis
        restart: always
        ports: 
            - "5001:3000"
        environment: 
            NODE_ENV: "production"
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_NAME: "user_profile"
            DB_HOST: "db"
            REDIS_HOST: "redis"     
    
    questions:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../microservices/questions
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.questions
        container_name: ms_questions
        depends_on: 
            - db
            - redis
        restart: always
        ports: 
            - "5002:3000"
        environment: 
            NODE_ENV: "production"
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_NAME: "questions"
            DB_HOST: "db"
            REDIS_HOST: "redis"  
        
    keywords:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../microservices/keywords
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.keywords
        container_name: ms_keywords
        depends_on: 
            - db
            - redis
        restart: always
        ports: 
            - "5003:3000"
        environment: 
            NODE_ENV: "production"
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_NAME: "keywords"
            DB_HOST: "db"
            REDIS_HOST: "redis"    

    answers:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../microservices/answers
            # Dockerfile path is relative to link
            dockerfile: ../docker/Dockerfile.answers
        container_name: ms_answers
        depends_on: 
            - db
            - redis
        restart: always
        ports: 
            - "5004:3000"
        environment: 
            NODE_ENV: "production"
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_NAME: "questions"
            DB_HOST: "db"
            REDIS_HOST: "redis"      
            
    frontend:
        build: 
            # Context path is relative to docker-compose file (I guess)
            context: ../frontend
            dockerfile:  ../docker/Dockerfile.frontend
            args:
                REACT_APP_BACKEND_TYPE: "microservices"
        container_name: ms_frontend
        restart: always
        ports: 
            - "4999:80"
